In [5]:
import matplotlib.pyplot as plt
import numpy as np
import torch
import os

In [11]:
vanilla_dir = "../experiments/outputs/2021-07-21_08-41_class_vanilla"
scaled_dir ="../experiments/outputs/2021-07-21_08-24_class_scaled_rho"

vanilla_metrics = torch.load(os.path.join(vanilla_dir, "metrics.pt")) 
scaled_metrics = torch.load(os.path.join(scaled_dir, "metrics.pt"))

In [13]:
scaled_metrics

{'forward_pass_count': [0,
  6400,
  12800,
  19200,
  25600,
  32000,
  38400,
  44800,
  51200,
  57600,
  64000,
  70400,
  76800,
  83200,
  89600,
  96000,
  102400,
  108800,
  115200,
  121600,
  128000,
  134400,
  140800,
  147200,
  153600,
  160000,
  166400,
  172800,
  179200,
  185600,
  192000,
  198400,
  204800,
  211200,
  217600,
  224000,
  230400,
  236800,
  243200,
  249600,
  256000,
  262400,
  268800,
  275200,
  281600,
  288000,
  294400,
  300800,
  307200,
  313600,
  319680],
 'validation_loss': [tensor([0.0182, 0.0182, 0.0182, 0.0182, 0.0182]),
  tensor([0.0562, 0.0536, 0.0855, 0.0812, 0.0547]),
  tensor([0.0393, 0.0500, 0.0539, 0.0825, 0.0575]),
  tensor([0.0344, 0.0420, 0.0646, 0.0613, 0.0543]),
  tensor([0.0851, 0.0540, 0.0428, 0.0695, 0.0523]),
  tensor([0.0491, 0.0588, 0.0350, 0.1039, 0.0459]),
  tensor([0.0476, 0.0799, 0.0536, 0.0688, 0.0495]),
  tensor([0.0868, 0.0451, 0.0616, 0.0516, 0.0307]),
  tensor([0.0515, 0.0709, 0.1046, 0.1174, 0.0584]),
 

In [28]:
import networkx as nx

G = nx.wheel_graph(5)
G.edges
list(G.neighbors(1))

[0, 2, 4]